// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const h6: string;
export const linksContainer: string;
export const container: string;
